### ISSUE TITLE
Woula

### ISSUE THREAD

**Issue by Visyix** [Daffax/Config-plugins#1]
Frère y'a rien dans ton repository comment tu veux que ça marche franchement ...
**éclatax**

**Comment by Daffax** [comment]
si c'est mais c'est écrit en blanc

**Comment by Daffax** [comment]
HOHOHOHO

**Comment by Daffax** [comment]
Je suis pas dac

**Comment by Visyix** [comment]
Problème réglé

**Comment by Daffax** [comment]
nn
j'ai une autre question

**Comment by Visyix** [comment]
C koa

**Comment by Daffax** [comment]
pourquoi ya rien dans mon repository

**Comment by Visyix** [comment]
Parce-que c'est écrit en contraste élevé

**Comment by Daffax** [comment]
ah
